///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace LastTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DontFill recording.
    /// </summary>
    [TestModule("a179e859-e328-44c0-8cff-67ece699d08a", ModuleType.Recording, 1)]
    public partial class DontFill : ITestModule
    {
        /// <summary>
        /// Holds an instance of the LastTestRepository repository.
        /// </summary>
        public static LastTestRepository repo = LastTestRepository.Instance;

        static DontFill instance = new DontFill();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DontFill()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DontFill Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Field is empty
            Report.Log(ReportLevel.Info, "Mouse", "Field is empty\r\nMouse Left Click item 'Trendyol.RegisterEmailInput' at 53;19.", repo.Trendyol.RegisterEmailInputInfo, new RecordItemIndex(0));
            repo.Trendyol.RegisterEmailInput.Click("53;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Trendyol.Container' at 734;442.", repo.Trendyol.ContainerInfo, new RecordItemIndex(1));
            repo.Trendyol.Container.Click("734;442");
            Delay.Milliseconds(0);
            
            // Fieltd is empty
            Report.Log(ReportLevel.Info, "Mouse", "Fieltd is empty\r\nMouse Left Click item 'Trendyol.RegisterPasswordInput' at 38;14.", repo.Trendyol.RegisterPasswordInputInfo, new RecordItemIndex(2));
            repo.Trendyol.RegisterPasswordInput.Click("38;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Trendyol.Container' at 734;442.", repo.Trendyol.ContainerInfo, new RecordItemIndex(3));
            repo.Trendyol.Container.Click("734;442");
            Delay.Milliseconds(0);
            
            // Indıcatıng tnat checkbox is empty
            Report.Log(ReportLevel.Info, "Mouse", "Indıcatıng tnat checkbox is empty\r\nMouse Left Click item 'Trendyol.EmptyCheckbox' at 151;8.", repo.Trendyol.EmptyCheckboxInfo, new RecordItemIndex(4));
            repo.Trendyol.EmptyCheckbox.Click("151;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Trendyol.SubmitButton' at 120;17.", repo.Trendyol.SubmitButtonInfo, new RecordItemIndex(5));
            repo.Trendyol.SubmitButton.Click("120;17");
            Delay.Milliseconds(0);
            
            // Assuming that "validation error" in the case question is error in screenshot
            Report.Log(ReportLevel.Info, "Validation", "Assuming that \"validation error\" in the case question is error in screenshot\r\nValidating AttributeEqual (Id='error-box-wrapper') on item 'Trendyol.ValidationError'.", repo.Trendyol.ValidationErrorInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.Trendyol.ValidationErrorInfo, "Id", "error-box-wrapper");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
