///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace LastTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnterBlankSpaces recording.
    /// </summary>
    [TestModule("2532692a-5249-45e3-984a-112d80639606", ModuleType.Recording, 1)]
    public partial class EnterBlankSpaces : ITestModule
    {
        /// <summary>
        /// Holds an instance of the LastTestRepository repository.
        /// </summary>
        public static LastTestRepository repo = LastTestRepository.Instance;

        static EnterBlankSpaces instance = new EnterBlankSpaces();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnterBlankSpaces()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnterBlankSpaces Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Trendyol.RegisterEmailInput' at 64;20.", repo.Trendyol.RegisterEmailInputInfo, new RecordItemIndex(0));
            repo.Trendyol.RegisterEmailInput.Click("64;20");
            Delay.Milliseconds(0);
            
            // First blank space is entered.
            Report.Log(ReportLevel.Info, "Keyboard", "First blank space is entered.\r\nKey sequence ' ' with focus on 'Trendyol.RegisterEmailInput'.", repo.Trendyol.RegisterEmailInputInfo, new RecordItemIndex(1));
            repo.Trendyol.RegisterEmailInput.PressKeys(" ");
            Delay.Milliseconds(0);
            
            // Second blank space is entered.
            Report.Log(ReportLevel.Info, "Keyboard", "Second blank space is entered.\r\nKey sequence ' ' with focus on 'Trendyol.RegisterEmailInput'.", repo.Trendyol.RegisterEmailInputInfo, new RecordItemIndex(2));
            repo.Trendyol.RegisterEmailInput.PressKeys(" ");
            Delay.Milliseconds(0);
            
            // Clicking empty field for not getting blocked by ids in history
            Report.Log(ReportLevel.Info, "Mouse", "Clicking empty field for not getting blocked by ids in history\r\nMouse Left Click item 'Trendyol.Container' at 734;442.", repo.Trendyol.ContainerInfo, new RecordItemIndex(3));
            repo.Trendyol.Container.Click("734;442");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Trendyol.RegisterPasswordInput' at 51;17.", repo.Trendyol.RegisterPasswordInputInfo, new RecordItemIndex(4));
            repo.Trendyol.RegisterPasswordInput.Click("51;17");
            Delay.Milliseconds(0);
            
            // First blank space is entered.
            Report.Log(ReportLevel.Info, "Keyboard", "First blank space is entered.\r\nKey sequence ' ' with focus on 'Trendyol.RegisterPasswordInput'.", repo.Trendyol.RegisterPasswordInputInfo, new RecordItemIndex(5));
            repo.Trendyol.RegisterPasswordInput.EnsureVisible();
            Keyboard.Press(" ");
            Delay.Milliseconds(0);
            
            // Second blank space is entered.
            Report.Log(ReportLevel.Info, "Keyboard", "Second blank space is entered.\r\nKey sequence ' ' with focus on 'Trendyol.RegisterPasswordInput'.", repo.Trendyol.RegisterPasswordInputInfo, new RecordItemIndex(6));
            repo.Trendyol.RegisterPasswordInput.EnsureVisible();
            Keyboard.Press(" ");
            Delay.Milliseconds(0);
            
            // Clicking empty field for not getting blocked by passwords in history
            Report.Log(ReportLevel.Info, "Mouse", "Clicking empty field for not getting blocked by passwords in history\r\nMouse Left Click item 'Trendyol.Container' at 734;442.", repo.Trendyol.ContainerInfo, new RecordItemIndex(7));
            repo.Trendyol.Container.Click("734;442");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Trendyol.SubmitButton' at 225;23.", repo.Trendyol.SubmitButtonInfo, new RecordItemIndex(8));
            repo.Trendyol.SubmitButton.Click("225;23");
            Delay.Milliseconds(0);
            
            // Assuming same error desired again.
            Report.Log(ReportLevel.Info, "Validation", "Assuming same error desired again.\r\nValidating AttributeEqual (Id='error-box-wrapper') on item 'Trendyol.ValidationError'.", repo.Trendyol.ValidationErrorInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.Trendyol.ValidationErrorInfo, "Id", "error-box-wrapper");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
