///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace LastTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the LastTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("96429a15-ec2e-46ea-af76-8f2bd400db6a")]
    public partial class LastTestRepository : RepoGenBaseFolder
    {
        static LastTestRepository instance = new LastTestRepository();
        LastTestRepositoryFolders.TrendyolAppFolder _trendyol;

        /// <summary>
        /// Gets the singleton class instance representing the LastTestRepository element repository.
        /// </summary>
        [RepositoryFolder("96429a15-ec2e-46ea-af76-8f2bd400db6a")]
        public static LastTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public LastTestRepository() 
            : base("LastTestRepository", "/", null, 0, false, "96429a15-ec2e-46ea-af76-8f2bd400db6a", ".\\RepositoryImages\\LastTestRepository96429a15.rximgres")
        {
            _trendyol = new LastTestRepositoryFolders.TrendyolAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("96429a15-ec2e-46ea-af76-8f2bd400db6a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Trendyol folder.
        /// </summary>
        [RepositoryFolder("ed0b30b7-be3d-43ba-bcc3-04401631b14e")]
        public virtual LastTestRepositoryFolders.TrendyolAppFolder Trendyol
        {
            get { return _trendyol; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class LastTestRepositoryFolders
    {
        /// <summary>
        /// The TrendyolAppFolder folder.
        /// </summary>
        [RepositoryFolder("ed0b30b7-be3d-43ba-bcc3-04401631b14e")]
        public partial class TrendyolAppFolder : RepoGenBaseFolder
        {
            LastTestRepositoryFolders.Wishlist_buttonsFolder _wishlist_buttons;
            LastTestRepositoryFolders.MyAccountContainerFolder _myaccountcontainer;
            RepoItemInfo _allfieldsinregistrationpageInfo;
            RepoItemInfo _registeremailinputInfo;
            RepoItemInfo _registerpasswordinputInfo;
            RepoItemInfo _emptycheckboxInfo;
            RepoItemInfo _submitbuttonInfo;
            RepoItemInfo _validationerrorInfo;
            RepoItemInfo _addtocartInfo;
            RepoItemInfo _product2Info;
            RepoItemInfo _addedtocartInfo;
            RepoItemInfo _buttonfav1Info;
            RepoItemInfo _wishlistInfo;
            RepoItemInfo _addedtowishlistInfo;
            RepoItemInfo _paddaddressboxtypflexcenterInfo;
            RepoItemInfo _sepetionaylaInfo;
            RepoItemInfo _continuetobuyInfo;
            RepoItemInfo _headerInfo;
            RepoItemInfo _containerInfo;
            RepoItemInfo _buyInfo;

            /// <summary>
            /// Creates a new Trendyol  folder.
            /// </summary>
            public TrendyolAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Trendyol", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "ed0b30b7-be3d-43ba-bcc3-04401631b14e", "")
            {
                _wishlist_buttons = new LastTestRepositoryFolders.Wishlist_buttonsFolder(this);
                _myaccountcontainer = new LastTestRepositoryFolders.MyAccountContainerFolder(this);
                _allfieldsinregistrationpageInfo = new RepoItemInfo(this, "AllFieldsInRegistrationPage", ".//div[#'login-register']/div[3]", ".//div[#'login-register']/div[3]", 30000, null, "b0d37fba-a76e-4bce-8c51-305d485f316a");
                _registeremailinputInfo = new RepoItemInfo(this, "RegisterEmailInput", ".//input[#'register-email']", ".//input[#'register-email']", 30000, null, "4e84087b-5f31-406c-a6a4-6638239a6b10");
                _registerpasswordinputInfo = new RepoItemInfo(this, "RegisterPasswordInput", ".//input[#'register-password-input']", ".//input[#'register-password-input']", 30000, null, "026f9076-a778-41a1-b16c-860356ccce04");
                _emptycheckboxInfo = new RepoItemInfo(this, "EmptyCheckbox", ".//div[#'login-register']//form[@action='https://www.trendyol.com/uyelik']/div[6]/div/div[2]", ".//div[#'login-register']//form/div[6]/div/div[2]", 30000, null, "3c364767-be98-4ec4-8d40-6121010c619a");
                _submitbuttonInfo = new RepoItemInfo(this, "SubmitButton", ".//div[#'login-register']//form[@action='https://www.trendyol.com/uyelik']/button", ".//div[#'login-register']//form/button", 30000, null, "b749d96b-4302-4164-abde-ee0436eabe00");
                _validationerrorInfo = new RepoItemInfo(this, "ValidationError", ".//div[#'error-box-wrapper']", ".//div[#'error-box-wrapper']", 30000, null, "7869d7b0-123e-4815-a005-274b1eebee07");
                _addtocartInfo = new RepoItemInfo(this, "AddToCart", ".//main[#'product-detail-app']/div/div[2]//button/div[@innertext='Sepete Ekle']", ".//main[#'product-detail-app']//div[@innertext='Sepete Ekle']", 30000, null, "710df0ad-5734-4b04-8512-aafc5f08705c");
                _product2Info = new RepoItemInfo(this, "Product2", ".//main[#'product-detail-app']/div/aside[1]/div[2]/div/div/div/div[8]/?/?/a[@href>'https://www.trendyol.com/']/?/?/img[@alt='']", ".//main[#'product-detail-app']/div/aside[1]/div[2]/div/div/div/div[8]/div/a[@href>'https://www.trendyol.com/']/div[1]/img[@alt='']", 30000, null, "c896d311-385c-4313-a57f-f0d368510efc");
                _addedtocartInfo = new RepoItemInfo(this, "AddedToCart", ".//div[#'account-navigation-container']/div/div[2]/div", ".//div[#'account-navigation-container']/div/div[2]/div", 30000, null, "19b7100f-cf02-4526-8bb1-ae04b5b24b5e");
                _buttonfav1Info = new RepoItemInfo(this, "ButtonFav1", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[6]/div/div/div[1]/button", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[6]/div/div/div[1]/button", 30000, null, "3c11df5f-6c0a-4ef6-9a60-7ed04d54a93f");
                _wishlistInfo = new RepoItemInfo(this, "Wishlist", ".//div[#'account-navigation-container']/div/a[@href>'https://www.trendyol.com/']/?/?/p[@innertext='Favorilerim']", ".//div[#'account-navigation-container']//p[@innertext='Favorilerim']", 30000, null, "399a6a42-0161-4f91-b4bb-f2ec755efa4f");
                _addedtowishlistInfo = new RepoItemInfo(this, "AddedToWishlist", ".//div[#'account-gw-favorites']/div/div[3]/div", ".//div[#'account-gw-favorites']/div/div[3]/div", 30000, null, "9cddb2bd-797d-4065-a5e8-dcaddb7f0600");
                _paddaddressboxtypflexcenterInfo = new RepoItemInfo(this, "PAddAddressBoxTyPFlexCenter", ".//div[#'p-layout']/div/div[2]/div[1]/div[2]/div[2]/div[1]", ".//div[#'p-layout']/div/div[2]/div[1]/div[2]/div[2]/div[1]", 30000, null, "52fd354a-3f19-4ec6-8768-340050c20698");
                _sepetionaylaInfo = new RepoItemInfo(this, "SepetiOnayla", ".//div[#'pb-container']/aside/div/div[5]/?/?/span[@innertext='Sepeti Onayla']", ".//div[#'pb-container']/aside/div/div[5]/a[@href>'https://www.trendyol.com/']/span[@innertext='Sepeti Onayla']", 30000, null, "dcee763e-beb5-4865-9e68-b81f1128a2ff");
                _continuetobuyInfo = new RepoItemInfo(this, "ContinueToBuy", ".//div[#'p-layout']/aside/div/button[2]", ".//div[#'p-layout']/aside/div/button[2]", 30000, null, "669252b4-5ae2-40e0-b28a-37e736a0e681");
                _headerInfo = new RepoItemInfo(this, "Header", ".//div[#'sticky-header']/div/div", ".//div[#'sticky-header']/div/div", 30000, null, "aef9f171-d3a2-40a6-87ec-d7714b1a16ee");
                _containerInfo = new RepoItemInfo(this, "Container", ".//div[#'container']", ".//div[#'container']", 30000, null, "5f0e7301-ef5c-4587-b2ee-9756a7354d0d");
                _buyInfo = new RepoItemInfo(this, "Buy", ".//div[#'pb-container']/aside/div/div[4]/a[@href>'https://www.trendyol.com/']", ".//div[#'pb-container']/aside/div/div[4]/a[@href>'https://www.trendyol.com/']", 30000, null, "114c4234-38a1-4210-ad03-af0056f73056");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ed0b30b7-be3d-43ba-bcc3-04401631b14e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ed0b30b7-be3d-43ba-bcc3-04401631b14e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AllFieldsInRegistrationPage item.
            /// </summary>
            [RepositoryItem("b0d37fba-a76e-4bce-8c51-305d485f316a")]
            public virtual Ranorex.DivTag AllFieldsInRegistrationPage
            {
                get
                {
                    return _allfieldsinregistrationpageInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AllFieldsInRegistrationPage item info.
            /// </summary>
            [RepositoryItemInfo("b0d37fba-a76e-4bce-8c51-305d485f316a")]
            public virtual RepoItemInfo AllFieldsInRegistrationPageInfo
            {
                get
                {
                    return _allfieldsinregistrationpageInfo;
                }
            }

            /// <summary>
            /// The RegisterEmailInput item.
            /// </summary>
            [RepositoryItem("4e84087b-5f31-406c-a6a4-6638239a6b10")]
            public virtual Ranorex.InputTag RegisterEmailInput
            {
                get
                {
                    return _registeremailinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterEmailInput item info.
            /// </summary>
            [RepositoryItemInfo("4e84087b-5f31-406c-a6a4-6638239a6b10")]
            public virtual RepoItemInfo RegisterEmailInputInfo
            {
                get
                {
                    return _registeremailinputInfo;
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item.
            /// </summary>
            [RepositoryItem("026f9076-a778-41a1-b16c-860356ccce04")]
            public virtual Ranorex.InputTag RegisterPasswordInput
            {
                get
                {
                    return _registerpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RegisterPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("026f9076-a778-41a1-b16c-860356ccce04")]
            public virtual RepoItemInfo RegisterPasswordInputInfo
            {
                get
                {
                    return _registerpasswordinputInfo;
                }
            }

            /// <summary>
            /// The EmptyCheckbox item.
            /// </summary>
            [RepositoryItem("3c364767-be98-4ec4-8d40-6121010c619a")]
            public virtual Ranorex.DivTag EmptyCheckbox
            {
                get
                {
                    return _emptycheckboxInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The EmptyCheckbox item info.
            /// </summary>
            [RepositoryItemInfo("3c364767-be98-4ec4-8d40-6121010c619a")]
            public virtual RepoItemInfo EmptyCheckboxInfo
            {
                get
                {
                    return _emptycheckboxInfo;
                }
            }

            /// <summary>
            /// The SubmitButton item.
            /// </summary>
            [RepositoryItem("b749d96b-4302-4164-abde-ee0436eabe00")]
            public virtual Ranorex.ButtonTag SubmitButton
            {
                get
                {
                    return _submitbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("b749d96b-4302-4164-abde-ee0436eabe00")]
            public virtual RepoItemInfo SubmitButtonInfo
            {
                get
                {
                    return _submitbuttonInfo;
                }
            }

            /// <summary>
            /// The ValidationError item.
            /// </summary>
            [RepositoryItem("7869d7b0-123e-4815-a005-274b1eebee07")]
            public virtual Ranorex.DivTag ValidationError
            {
                get
                {
                    return _validationerrorInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ValidationError item info.
            /// </summary>
            [RepositoryItemInfo("7869d7b0-123e-4815-a005-274b1eebee07")]
            public virtual RepoItemInfo ValidationErrorInfo
            {
                get
                {
                    return _validationerrorInfo;
                }
            }

            /// <summary>
            /// The AddToCart item.
            /// </summary>
            [RepositoryItem("710df0ad-5734-4b04-8512-aafc5f08705c")]
            public virtual Ranorex.DivTag AddToCart
            {
                get
                {
                    return _addtocartInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AddToCart item info.
            /// </summary>
            [RepositoryItemInfo("710df0ad-5734-4b04-8512-aafc5f08705c")]
            public virtual RepoItemInfo AddToCartInfo
            {
                get
                {
                    return _addtocartInfo;
                }
            }

            /// <summary>
            /// The Product2 item.
            /// </summary>
            [RepositoryItem("c896d311-385c-4313-a57f-f0d368510efc")]
            public virtual Ranorex.ImgTag Product2
            {
                get
                {
                    return _product2Info.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Product2 item info.
            /// </summary>
            [RepositoryItemInfo("c896d311-385c-4313-a57f-f0d368510efc")]
            public virtual RepoItemInfo Product2Info
            {
                get
                {
                    return _product2Info;
                }
            }

            /// <summary>
            /// The AddedToCart item.
            /// </summary>
            [RepositoryItem("19b7100f-cf02-4526-8bb1-ae04b5b24b5e")]
            public virtual Ranorex.DivTag AddedToCart
            {
                get
                {
                    return _addedtocartInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AddedToCart item info.
            /// </summary>
            [RepositoryItemInfo("19b7100f-cf02-4526-8bb1-ae04b5b24b5e")]
            public virtual RepoItemInfo AddedToCartInfo
            {
                get
                {
                    return _addedtocartInfo;
                }
            }

            /// <summary>
            /// The ButtonFav1 item.
            /// </summary>
            [RepositoryItem("3c11df5f-6c0a-4ef6-9a60-7ed04d54a93f")]
            public virtual Ranorex.ButtonTag ButtonFav1
            {
                get
                {
                    return _buttonfav1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonFav1 item info.
            /// </summary>
            [RepositoryItemInfo("3c11df5f-6c0a-4ef6-9a60-7ed04d54a93f")]
            public virtual RepoItemInfo ButtonFav1Info
            {
                get
                {
                    return _buttonfav1Info;
                }
            }

            /// <summary>
            /// The Wishlist item.
            /// </summary>
            [RepositoryItem("399a6a42-0161-4f91-b4bb-f2ec755efa4f")]
            public virtual Ranorex.PTag Wishlist
            {
                get
                {
                    return _wishlistInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Wishlist item info.
            /// </summary>
            [RepositoryItemInfo("399a6a42-0161-4f91-b4bb-f2ec755efa4f")]
            public virtual RepoItemInfo WishlistInfo
            {
                get
                {
                    return _wishlistInfo;
                }
            }

            /// <summary>
            /// The AddedToWishlist item.
            /// </summary>
            [RepositoryItem("9cddb2bd-797d-4065-a5e8-dcaddb7f0600")]
            public virtual Ranorex.DivTag AddedToWishlist
            {
                get
                {
                    return _addedtowishlistInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AddedToWishlist item info.
            /// </summary>
            [RepositoryItemInfo("9cddb2bd-797d-4065-a5e8-dcaddb7f0600")]
            public virtual RepoItemInfo AddedToWishlistInfo
            {
                get
                {
                    return _addedtowishlistInfo;
                }
            }

            /// <summary>
            /// The PAddAddressBoxTyPFlexCenter item.
            /// </summary>
            [RepositoryItem("52fd354a-3f19-4ec6-8768-340050c20698")]
            public virtual Ranorex.DivTag PAddAddressBoxTyPFlexCenter
            {
                get
                {
                    return _paddaddressboxtypflexcenterInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PAddAddressBoxTyPFlexCenter item info.
            /// </summary>
            [RepositoryItemInfo("52fd354a-3f19-4ec6-8768-340050c20698")]
            public virtual RepoItemInfo PAddAddressBoxTyPFlexCenterInfo
            {
                get
                {
                    return _paddaddressboxtypflexcenterInfo;
                }
            }

            /// <summary>
            /// The SepetiOnayla item.
            /// </summary>
            [RepositoryItem("dcee763e-beb5-4865-9e68-b81f1128a2ff")]
            public virtual Ranorex.SpanTag SepetiOnayla
            {
                get
                {
                    return _sepetionaylaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SepetiOnayla item info.
            /// </summary>
            [RepositoryItemInfo("dcee763e-beb5-4865-9e68-b81f1128a2ff")]
            public virtual RepoItemInfo SepetiOnaylaInfo
            {
                get
                {
                    return _sepetionaylaInfo;
                }
            }

            /// <summary>
            /// The ContinueToBuy item.
            /// </summary>
            [RepositoryItem("669252b4-5ae2-40e0-b28a-37e736a0e681")]
            public virtual Ranorex.ButtonTag ContinueToBuy
            {
                get
                {
                    return _continuetobuyInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ContinueToBuy item info.
            /// </summary>
            [RepositoryItemInfo("669252b4-5ae2-40e0-b28a-37e736a0e681")]
            public virtual RepoItemInfo ContinueToBuyInfo
            {
                get
                {
                    return _continuetobuyInfo;
                }
            }

            /// <summary>
            /// The Header item.
            /// </summary>
            [RepositoryItem("aef9f171-d3a2-40a6-87ec-d7714b1a16ee")]
            public virtual Ranorex.DivTag Header
            {
                get
                {
                    return _headerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Header item info.
            /// </summary>
            [RepositoryItemInfo("aef9f171-d3a2-40a6-87ec-d7714b1a16ee")]
            public virtual RepoItemInfo HeaderInfo
            {
                get
                {
                    return _headerInfo;
                }
            }

            /// <summary>
            /// The Container item.
            /// </summary>
            [RepositoryItem("5f0e7301-ef5c-4587-b2ee-9756a7354d0d")]
            public virtual Ranorex.DivTag Container
            {
                get
                {
                    return _containerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Container item info.
            /// </summary>
            [RepositoryItemInfo("5f0e7301-ef5c-4587-b2ee-9756a7354d0d")]
            public virtual RepoItemInfo ContainerInfo
            {
                get
                {
                    return _containerInfo;
                }
            }

            /// <summary>
            /// The Buy item.
            /// </summary>
            [RepositoryItem("114c4234-38a1-4210-ad03-af0056f73056")]
            public virtual Ranorex.ATag Buy
            {
                get
                {
                    return _buyInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Buy item info.
            /// </summary>
            [RepositoryItemInfo("114c4234-38a1-4210-ad03-af0056f73056")]
            public virtual RepoItemInfo BuyInfo
            {
                get
                {
                    return _buyInfo;
                }
            }

            /// <summary>
            /// The Wishlist_buttons folder.
            /// </summary>
            [RepositoryFolder("99cfa4b4-c3e4-4b16-9331-68157860b804")]
            public virtual LastTestRepositoryFolders.Wishlist_buttonsFolder Wishlist_buttons
            {
                get { return _wishlist_buttons; }
            }

            /// <summary>
            /// The MyAccountContainer folder.
            /// </summary>
            [RepositoryFolder("157d7f0a-0bb7-4095-aff5-63d39c934791")]
            public virtual LastTestRepositoryFolders.MyAccountContainerFolder MyAccountContainer
            {
                get { return _myaccountcontainer; }
            }
        }

        /// <summary>
        /// The Wishlist_buttonsFolder folder.
        /// </summary>
        [RepositoryFolder("99cfa4b4-c3e4-4b16-9331-68157860b804")]
        public partial class Wishlist_buttonsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _iheartorangeInfo;
            RepoItemInfo _buttonfav2Info;
            RepoItemInfo _buttonfav3Info;
            RepoItemInfo _buttonfav4Info;

            /// <summary>
            /// Creates a new Wishlist_buttons  folder.
            /// </summary>
            public Wishlist_buttonsFolder(RepoGenBaseFolder parentFolder) :
                    base("Wishlist_buttons", ".//main[#'product-detail-app']/div/aside[1]/div[2]/div/div/div", parentFolder, 30000, null, false, "99cfa4b4-c3e4-4b16-9331-68157860b804", "")
            {
                _iheartorangeInfo = new RepoItemInfo(this, "IHeartOrange", "div[8]//button/i", "div[8]/div/div/button/i", 30000, null, "b2bc8fdc-2e36-4e44-a33c-f5c125c7178f");
                _buttonfav2Info = new RepoItemInfo(this, "ButtonFav2", "div[8]//button", "div[8]/div/div/button", 30000, null, "2dea010f-9e7b-48fd-a979-4f1ffe4832a7");
                _buttonfav3Info = new RepoItemInfo(this, "ButtonFav3", "div[6]//button", "div[6]/div/div/button", 30000, null, "57456605-4500-4a9f-9a8e-a88b6a3f38ec");
                _buttonfav4Info = new RepoItemInfo(this, "ButtonFav4", "div[7]//button", "div[7]/div/div/button", 30000, null, "0afab07e-11b0-43c6-a98c-0035ee377cfd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("99cfa4b4-c3e4-4b16-9331-68157860b804")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("99cfa4b4-c3e4-4b16-9331-68157860b804")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IHeartOrange item.
            /// </summary>
            [RepositoryItem("b2bc8fdc-2e36-4e44-a33c-f5c125c7178f")]
            public virtual Ranorex.ITag IHeartOrange
            {
                get
                {
                    return _iheartorangeInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IHeartOrange item info.
            /// </summary>
            [RepositoryItemInfo("b2bc8fdc-2e36-4e44-a33c-f5c125c7178f")]
            public virtual RepoItemInfo IHeartOrangeInfo
            {
                get
                {
                    return _iheartorangeInfo;
                }
            }

            /// <summary>
            /// The ButtonFav2 item.
            /// </summary>
            [RepositoryItem("2dea010f-9e7b-48fd-a979-4f1ffe4832a7")]
            public virtual Ranorex.ButtonTag ButtonFav2
            {
                get
                {
                    return _buttonfav2Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonFav2 item info.
            /// </summary>
            [RepositoryItemInfo("2dea010f-9e7b-48fd-a979-4f1ffe4832a7")]
            public virtual RepoItemInfo ButtonFav2Info
            {
                get
                {
                    return _buttonfav2Info;
                }
            }

            /// <summary>
            /// The ButtonFav3 item.
            /// </summary>
            [RepositoryItem("57456605-4500-4a9f-9a8e-a88b6a3f38ec")]
            public virtual Ranorex.ButtonTag ButtonFav3
            {
                get
                {
                    return _buttonfav3Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonFav3 item info.
            /// </summary>
            [RepositoryItemInfo("57456605-4500-4a9f-9a8e-a88b6a3f38ec")]
            public virtual RepoItemInfo ButtonFav3Info
            {
                get
                {
                    return _buttonfav3Info;
                }
            }

            /// <summary>
            /// The ButtonFav4 item.
            /// </summary>
            [RepositoryItem("0afab07e-11b0-43c6-a98c-0035ee377cfd")]
            public virtual Ranorex.ButtonTag ButtonFav4
            {
                get
                {
                    return _buttonfav4Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonFav4 item info.
            /// </summary>
            [RepositoryItemInfo("0afab07e-11b0-43c6-a98c-0035ee377cfd")]
            public virtual RepoItemInfo ButtonFav4Info
            {
                get
                {
                    return _buttonfav4Info;
                }
            }
        }

        /// <summary>
        /// The MyAccountContainerFolder folder.
        /// </summary>
        [RepositoryFolder("157d7f0a-0bb7-4095-aff5-63d39c934791")]
        public partial class MyAccountContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginInfo;
            RepoItemInfo _myaccountInfo;
            RepoItemInfo _logoutInfo;

            /// <summary>
            /// Creates a new MyAccountContainer  folder.
            /// </summary>
            public MyAccountContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("MyAccountContainer", ".//div[#'account-navigation-container']/div/div[1]", parentFolder, 30000, null, false, "157d7f0a-0bb7-4095-aff5-63d39c934791", "")
            {
                _loginInfo = new RepoItemInfo(this, "Login", "?/?/p[@innertext='Giriş Yap']", "", 30000, null, "e974d6ac-a40f-4606-97b8-7b7ac2418235");
                _myaccountInfo = new RepoItemInfo(this, "MyAccount", "?/?/p[@innertext='Hesabım']", "", 30000, null, "02601e55-a015-4bbe-bd04-a6cb5c7e7ddd");
                _logoutInfo = new RepoItemInfo(this, "Logout", "div[2]/div/a[9]/p[@innertext='Çıkış Yap']", "", 30000, null, "86202470-95bb-4064-bb59-3f278e4d3f29");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("157d7f0a-0bb7-4095-aff5-63d39c934791")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("157d7f0a-0bb7-4095-aff5-63d39c934791")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("e974d6ac-a40f-4606-97b8-7b7ac2418235")]
            public virtual Ranorex.PTag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("e974d6ac-a40f-4606-97b8-7b7ac2418235")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The MyAccount item.
            /// </summary>
            [RepositoryItem("02601e55-a015-4bbe-bd04-a6cb5c7e7ddd")]
            public virtual Ranorex.PTag MyAccount
            {
                get
                {
                    return _myaccountInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The MyAccount item info.
            /// </summary>
            [RepositoryItemInfo("02601e55-a015-4bbe-bd04-a6cb5c7e7ddd")]
            public virtual RepoItemInfo MyAccountInfo
            {
                get
                {
                    return _myaccountInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("86202470-95bb-4064-bb59-3f278e4d3f29")]
            public virtual Ranorex.PTag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("86202470-95bb-4064-bb59-3f278e4d3f29")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
