///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace LastTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Logout recording.
    /// </summary>
    [TestModule("d71b3818-c85f-4578-93bf-20843a13cac4", ModuleType.Recording, 1)]
    public partial class Logout : ITestModule
    {
        /// <summary>
        /// Holds an instance of the LastTestRepository repository.
        /// </summary>
        public static LastTestRepository repo = LastTestRepository.Instance;

        static Logout instance = new Logout();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Logout()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Logout Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(0));
            Delay.Duration(500, false);
            
            // Cursor needs to stay on that section
            Report.Log(ReportLevel.Info, "Mouse", "Cursor needs to stay on that section\r\nMouse None Move item 'Trendyol.MyAccountContainer.MyAccount' at 27;3.", repo.Trendyol.MyAccountContainer.MyAccountInfo, new RecordItemIndex(1));
            repo.Trendyol.MyAccountContainer.MyAccount.MoveTo("27;3");
            Delay.Milliseconds(0);
            
            // Delays are necessary for logout sections loading
            Report.Log(ReportLevel.Info, "Delay", "Delays are necessary for logout sections loading\r\nWaiting for 500ms.", new RecordItemIndex(2));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'Trendyol.MyAccountContainer.Logout' at 48;14.", repo.Trendyol.MyAccountContainer.LogoutInfo, new RecordItemIndex(3));
            repo.Trendyol.MyAccountContainer.Logout.MoveTo("48;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(4));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Trendyol.MyAccountContainer.Logout' at 48;14.", repo.Trendyol.MyAccountContainer.LogoutInfo, new RecordItemIndex(5));
            repo.Trendyol.MyAccountContainer.Logout.Click("48;14");
            Delay.Milliseconds(0);
            
            // Verifys that logout is succesful. ( since logining is posible. )
            Report.Log(ReportLevel.Info, "Validation", "Verifys that logout is succesful. ( since logining is posible. )\r\nValidating AttributeEqual (InnerText='Giriş Yap') on item 'Trendyol.MyAccountContainer.Login'.", repo.Trendyol.MyAccountContainer.LoginInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.Trendyol.MyAccountContainer.LoginInfo, "InnerText", "Giriş Yap");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
