///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace LastTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ReportingForCase8 recording.
    /// </summary>
    [TestModule("0b7f6f1c-0f9b-4b2b-86f7-15505280d349", ModuleType.Recording, 1)]
    public partial class ReportingForCase8 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the LastTestRepository repository.
        /// </summary>
        public static LastTestRepository repo = LastTestRepository.Instance;

        static ReportingForCase8 instance = new ReportingForCase8();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ReportingForCase8()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ReportingForCase8 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // It reports the first question's answer in Trendyol Help section ( https://www.trendyol.com/yardim/sorular )
            Report.Log(ReportLevel.Info, "User", "• İade adımları:\r\n\r\n1. trendyol.com ve mobil uygulamalarda yer alan \"Hesabım\" bölümünden “Siparişlerim'e“ gidin.\r\n\r\n2. “Detaylar” butonuna basın ve siparişinizin detaylarını görüntüleyin.\r\n\r\n3. \"Kolay İade Talebi Oluştur\" butonuna basın.\r\n\r\n4. İade edilecek ürün ve iade nedeni seçin. Aynı üründen birden fazla satın aldıysanız iade edilecek ürün adedini de seçmeniz gerekir.\r\n\r\n5. Kargo seçiminizi yapın.\r\n\r\n6. Ekranda çıkan iade kargo kodunu not alın. İade kargo kodunuza \"Siparişlerim\" sayfasından ve üyelik mail adresinize gönderilen bilgilendirme mesajından da ulaşabilirsiniz.\r\n\r\n7. İade edilecek ürünler ile birlikte faturayı tek bir pakete koyun. (Her bir teslimat için iade kodu ayrı ayrı alınmalı ve paketler ayrı ayrı hazırlanarak kargoya verilmelidir.)\r\n\r\n• Faturanız yoksa aşağıdaki bilgileri boş bir kağıda yazıp iade paketinin içine koyup iadenizi yapabilirsiniz.\r\n\r\no Ad Soyad:\r\n\r\no Sipariş No:\r\n\r\no İade Nedeni:\r\n\r\n8. Paketi iade kargo koduyla birlikte seçtiğiniz kargoya 7 gün içinde teslim edin. Kodu vermeniz yeterlidir, ayrıca bir İade adresi belirtmeniz gerekmez. 7 günü geçirdiğiniz durumda yeniden iade kargo kodu almalısınız.", new RecordItemIndex(0));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
